### ISSUE TITLE
Add a META description, keywords, and author to the index.html page

### ISSUE THREAD

**Issue by tkshill** [tkshill/Quarto#56]
# Issue Context
Best Practices agree that we should format  HTML in a way that enables crawlers to better understand your app’s content.
Currently the document does not have a meta description. Meta descriptions may be included in search results to concisely summarize page content. We should also include keywords and author meta tags.

# Suggested Solution
In the head of the `index.html` file in the `public folder`
- [ ] Add a meta description using the text in the about section of the quarto [main page](https://github.com/tkshill/Quarto)
- [ ] Add a meta keywords section using the tags in the about section of the quarto main page
- [ ] Add an author meta tag with the author name as "Kirk Shillingford"

# Alternatives Considered
Not sure if there are other keywords to be considered for SEO optimization That might also be something to research.

# Additional Resources
[w3 schools](https://www.w3schools.com/tags/tag_meta.asp) has a concise write up (and examples) of using meta tags
---
See [here](https://github.com/tkshill/Quarto/blob/main/README.md#run-and-install) in the read me for how to run and install the application.

See [here](https://github.com/tkshill/Quarto/blob/main/CONTRIBUTING.md#the-basics) in contributing for the basics on forking and cloning the repository.

**Comment by tmillerj** [comment]
Hello, I'd like to tackle this issue for the project.

**Comment by tkshill** [comment]
Accidentally responded to the PR before responding here! Thank you very much for fixing this!
